inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import Index , SignUpView ,DashboardView,CreateItemView,UpdateItem,DeleteItem
from django.contrib.auth import views as auth_views
app_name='inventory'
urlpatterns = [
   
    path('',Index.as_view(),name="index"),
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('signup/',SignUpView.as_view(),name="signup"),
    path('login/',auth_views.LoginView.as_view(template_name='inventory/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='inventory/logout.html'),name='logout'),
    path('add-item/',CreateItemView.as_view(),name='add-item'),
    path("item-update/<int:pk>/", UpdateItem.as_view(), name="item-update"),
    path('item/<int:pk>/delete/',DeleteItem.as_view(),name='delete-item')
]

inventoryManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/',include('inventory.urls'))
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Teacher(models.Model):
    name=models.CharField(max_length=80)
    age=models.IntegerField()
class Category(models.Model):
    name=models.CharField(max_length=200)
    class Meta:
        verbose_name_plural='categories'
    def __str__(self):
        return self.name
class InventoryItem(models.Model):
    name=models.CharField(max_length=200)
    quantity=models.IntegerField()
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,blank=True,null=True)
    date_created=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

    

        

inventory/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import InventoryItem , Category
class UserRegisterForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username','email','password1','password2']
        
        
class AddItemForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all())

    class Meta:
        model = InventoryItem
        fields=['name','quantity','category']
        #we need the category form to add it
        '''
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields["categories"].queryset = Catgory.objectcis.all() 
        '''     

inventory/views.py
from django.shortcuts import render ,redirect
from django.http import HttpRequest
from django.contrib.auth import login, authenticate
from django.views.generic.base import TemplateView , View
from .forms import UserRegisterForm , AddItemForm
from .models import InventoryItem,Category
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView , UpdateView ,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
# Create your views here.
class Index(TemplateView):
    template_name="inventory/index.html"

class DashboardView(LoginRequiredMixin,View):
    login_url = '/inventory/login/'
    def get(self,request):
        Useritmes=InventoryItem.objects.filter(user=self.request.user.id).order_by('id')
        return render(request,'inventory/dashboard.html',{'items':Useritmes})
    def post(self,request):
        pass
        
class SignUpView(View):
    def get(self,request):
         form=UserRegisterForm()
         return render(request,'inventory/signup.html',{
             'form' :form
         })
    def post(self,request):
        form =UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('inventory:index')
        return render(request,'inventory/signup.html',{'form':form})
        
class CreateItemView(LoginRequiredMixin,CreateView):
    template_name='inventory/AddItem_form.html'
    form_class=AddItemForm
    success_url='/inventory/dashboard/'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context['name']='sanaa'
        return context
    
    def form_valid(self,form):
        print(form)
        form.instance.user=self.request.user
        return super().form_valid(form)
class UpdateItem(LoginRequiredMixin,UpdateView):
    model=InventoryItem
    template_name='inventory/AddItem_form.html'
    form_class=AddItemForm
    success_url='/inventory/dashboard/'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
       
        return context
     
    def form_valid(self,form):
        
        form.instance.user=self.request.user
        return super().form_valid(form)
    
class DeleteItem(LoginRequiredMixin,DeleteView):
    #model =InventoryItem
    template_name='inventory/DeletItem.html'
    success_url = reverse_lazy("inventory:dashboard")
    context_object_name='items'
    queryset=InventoryItem.objects.all()
    def form_valid(self,form):
        messages.success(self.request, "The Item was deleted successfully.")
        return super().form_valid(form)
    
                

inventory/templates/inventory/AddItem_form.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add Item To Inventory Management{% endblock title %}
{% include 'inventory/navbar.html' %}
{% block bodyContent %}

<div class="row">
    <div class="col-md-4 mt-5">
        <form method="post">
        {% csrf_token%}
{{ form|crispy }}
<button class="btn btn-primary" type="submit">add item</button>
        </form>
    </div>

</div>
{% endblock bodyContent %}

inventory/templates/inventory/DeletItem.html
{% extends 'inventory/base.html' %}

{% block title %} Delete Item {%endblock title %}

{% block bodyContent %}

<div class="row">
<div class="col-md-12 mt-5">
<form method="post">
    {% csrf_token %}

    <h1> Are You sure you want to delete {{items.category }} ? </h1>   
<button type="submit" class="btn btn-primary" >Submit</button>

</form>
</div>
</div>

{% include 'inventory/navbar.html  ' %}

{% endblock bodyContent %}

inventory/templates/inventory/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %} {% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'inventory/css/bootstrap.min.css' %}">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
{% block bodyContent %}


{%  endblock bodyContent %}

  </body>
</html>

inventory/templates/inventory/dashboard.html
{% extends 'inventory/base.html' %}
{% block title %} Dashboard {% endblock title %}
{% block bodyContent %}
{% include 'inventory/navbar.html '%}

<div class="row">
<div class="col-md-10 col-12 mx-auto mt-5">
<div class="d-flex justify-content-end">
<a href="{% url 'inventory:add-item' %}" class="btn btn-primary">+</a>
</div>
{{ itmes }}
<table class="table table-hover table-striped">
<thead>
<tr>
<th scope="col">ID</th>
<th scope="col">Name</th>
<th scope="col">Qte</th>
<th scope="col">Category</th>


</tr>
</thead>
<tbody>
    {% if items  %}
<tr>
    <th scope="row">-</th>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
{% endif %}
{% for item in items %}
<tr>
<th scope="row">{{ item.id }}</th>
<td>{{item.name}}</td>
<td>{{item.quantity}}</td>
<td>{{item.category.name}}</td>
<td> <a href="{%url 'inventory:item-update' item.id %}" class="btn btn-primary">Update Item</a></td>
<td><a href="{% url 'inventory:delete-item'  item.id %}" class="btn btn-primary">Delete Item</a></td>
</tr>
{% endfor %}
</tbody>
</table>

</div>
</div>
{% endblock bodyContent %}

inventory/templates/inventory/footer.html
<footer>
 
</footer>

inventory/templates/inventory/header.html
<header>

</header>

inventory/templates/inventory/index.html
{% extends 'inventory/base.html' %}
{% block title %} Welcome to Inventory Home Page {% endblock title %}
{% block bodyContent %}
{% include 'inventory/header.html' %}

<h1> Welcome</h1>
{% include 'inventory/navbar.html' %}

<div class="row"> 
     <div class="col-md-4 mt-5"></div>

<h1 class="fw-light">Track And Manage your Inventory</h1>
<p>Kep track of your inventory and recive quantity alerts for low invntory</p>    

<div>
<a href="{% url 'inventory:dashboard' %}" class="btn btn-primary">Get Startde Now!</a>

</div>
</div>
    </div>
{% include 'inventory/footer.html' %}
{% endblock bodyContent %}

inventory/templates/inventory/login.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}

{%  block bodyContent %}

<div class="row  justify-content-center">
    <div class="col-md-4 mt-5">

        <h1>Log In</h1>

        <form method="post">
{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-outline-secondary" type="submit">Sign in</button>
        </form>


    <div>
        <small class="text-muted">Need an accout ?<a href="{% url 'inventory:signup' %}">Sign up</a></small>
    </div>
    </div>


</div>

{% endblock bodyContent %}

inventory/templates/inventory/logout.html
{% extends 'inventory/base.html' %}

{% block title %} Log Out User{% endblock title %}

{% block bodyContent %}

<div class="row  justify-content-center">
    <div class="col-md-4 mt-5">
        <h1>You Are Log Out </h1>
<div><strong class="text-bold">log In to Your Account<a href="{% url 'inventory:login' %}"> Sign In</a> </strong></div>
<div><small class="text-muted">Need an accout ?<a href="{% url 'inventory:signup' %}">Sign up</a></small></div>


</div>


</div>
{% endblock bodyContent%}

inventory/templates/inventory/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'inventory:index' %}">Inventory Manager</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
       {% if user.is_authenticated %}
          <li class="nav-item">
{{ user.username }}       
   </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:logout'%}">Log Out</a>
          </li>
      {% else %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'inventory:login' %}">Sign In</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{% url 'inventory:signup' %}"> Sign Up </a>
</a>
</li>
      {% endif %}
        </ul>
      </div>
    </div>
  </nav>

inventory/templates/inventory/signup.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up Page {% endblock title%}

{% block bodyContent %} 

<div class="row">
    <div class="col-md-4 mx-auto mt-5">
        <h1>Sign up User</h1>
        {% if form.erros %}
        {% for field in form %}
        {% for error in field.erros %}
        <div class="alert alert-danger">

            <strong>{{ error|escape }}</strong>

        </div>
        {% endfor %}
        {% endfor %}

        {% for error in form.non_field_erros %}
        <div class="alert alert-danger">

            <strong>{{ error|escape }}</strong>

        </div>
        {% endfor %}
        {% endif %}
        <form method="post">
{% csrf_token %}

{{ form | crispy}}
<button class="btn btn-primary" type="submit" >
    Sign Up
</button>
        </form>
    </div>
</div>
{%endblock bodyContent%}